import React from "react"; // Bu sətri əlavə etdik ki, xəta getsin
import type { Metadata } from "next";
import "./globals.css";

// import "./globals.css";  <-- Bu sətri sildik və ya şərhə aldıq ki, hələ xəta verməsin

export const metadata: Metadata = {
  title: "Metadata Engine",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}